### ISSUE TITLE
Capistrano

### ISSUE THREAD

**Issue by flavray** [zeta-inc/zeta-books-api#7]
Capify the project & create capistrano infrastructure on the AWS

**Comment by Thooms** [comment]
Capified the projet, checking everything is fine and writing a pull request.

**Comment by Thooms** [comment]
Works quite fine, except for that little issue at step asset:precompile. We do not need any assets management for now, so I think we can disable it. Will do it asap (there some files to add iirc).

**Comment by flavray** [comment]
It was a rbenv issue, solved :)
